# Arquivo de configuração do sistema

saida:
  diretorio: "resultados/"   # Pasta onde os arquivos serão salvos

periodo:
  data_inicio: "2023-01-01"
  data_final: "2023-12-31"

empresa:
  codigo: "PETR4.SA"
  nome: "Petrobras"
  setor: "Petróleo e Gás"
